import os
from datetime import datetime
from typing import Optional, List

from cpp.cpp_function import CppFunction
from cpp.helper import CamelCase2snake_case


class CppClass:

    def __init__(self, class_name: str, derived_from_class: Optional[str], includes: str, virtual=False, namespace=None):
        self.class_name = class_name
        self.derived_from_class = derived_from_class
        self.includes = includes
        self.functions: List[CppFunction] = []
        self.filename = CamelCase2snake_case(class_name)
        self.constructor_arguments = None
        self.constructor_code = None
        self.has_constructor = False
        self.member_lines = []
        self.virtual = virtual

    def add_member(self, member_line: str):
        self.member_lines.append(member_line)

    def add_constructor(self, arguments: str, code: str):
        self.constructor_arguments = arguments
        self.constructor_code = code
        self.has_constructor = True

    def add_function(self, function: CppFunction):
        self.functions.append(function)

    def add_functions(self, functions: List[CppFunction]):
        self.functions += functions

    def get_implementation(self):
        if len(self.functions) == 0:
            raise RuntimeError("Can not generate cpp implementation without any function!")

        cpp_code = f"#include \"{self.filename}.h\"\n\n"

        if self.has_constructor:
            cpp_code += f"{self.class_name}::{self.class_name}({self.constructor_arguments}) ""{\n"
            for l in self.constructor_code.splitlines():
                cpp_code += f"\t{l}\n"
            cpp_code += "};\n\n"

        for f in self.functions:
            cpp_code += f.get_implementation(self.class_name) + "\n\n"
        return cpp_code

    def get_definition_file(self):
        if len(self.functions) == 0:
            raise RuntimeError("Can not generate cpp definition without any function!")

        derived_str = ""
        if self.derived_from_class:
            derived_str = f" : public {self.derived_from_class}"
        cpp_code = f"// generated by Designwerk EXI Converter {datetime.now()}\n" \
                   f"#pragma once\n\n{self.includes}\n\n" \
                   f"class {self.class_name}{derived_str} ""{\n" \
                   f"  public:\n\n"

        if self.has_constructor:
            cpp_code += f"\t{self.class_name}({self.constructor_arguments});\n"
            if self.virtual:
                cpp_code += f"\tvirtual ~{self.class_name}() = default;  // LCOV_EXCL_LINE\n"

        for f in self.functions:
            cpp_code += "\n" + f.get_definition(virtual_function=self.virtual) + "\n"

        if len(self.member_lines) > 0:
            cpp_code += "\n  private:\n"
            for m in self.member_lines:
                cpp_code += f"\t{m}\n"

        cpp_code += "};\n"

        return cpp_code

    def write_cpp(self, directory: str):
        with open(os.path.join(directory, self.filename + ".cpp"), "w") as f:
            f.write(self.get_implementation())

    def write_h(self, directory: str):
        with open(os.path.join(directory, self.filename + ".h"), "w") as f:
            f.write(self.get_definition_file())
