// generated by Designwerk EXI Converter 2022-06-30 13:16:19.436388
#pragma once

#include <cstdint>
#include <cstdio>
#include <string>
#include "base/bitstream.h"
#include "base/input_string_stream.h"


class BaseTypes {
public:

    BaseTypes(BitStream * bit_stream);
    BaseTypes(BitStream * bit_stream, InputStringStream * input_string_stream);
    virtual ~BaseTypes() = default;  // LCOV_EXCL_LINE

    virtual void injectHexBin(uint8_t max_length);

    virtual std::string extractHexBin(uint8_t max_length);

    virtual uint32_t extractNBitsForEnum(uint32_t n_bits);

    virtual void injectNBitsForEnum(uint8_t value, uint8_t n_bits);

    virtual void injectString();

    virtual std::string extractString();

    virtual void injectUri();

    virtual std::string extractUri();

    virtual void injectIntegerNumber(uint8_t n_bytes, bool is_unsigned);

    virtual int32_t extractIntegerNumber(uint8_t n_bytes, bool is_unsigned);

    virtual void injectBase64Value();

    virtual std::string extractBase64Value();

    // / \brief writes the given boolean value to the bitstream
    virtual void injectBoolValue();

    // / \brief read a bit from bitstream and returns the interpreted value
    virtual bool extractBoolValue();

    virtual void injectNBitNumber(uint8_t n_bits, int32_t offset);

    virtual int32_t extractNBitNumber(uint8_t n_bits, int32_t offset);

    virtual void check_event_code_is_0(std::string current_type_name);

    virtual uint8_t get_event_code_with_n_bits(int8_t n_bits, std::string current_type_name);

    virtual void add_event_code(std::string current_type_name);

    virtual void add_event_code_with_n_bits(int8_t event_code, int8_t n_bits, std::string current_type_name);

private:
    BitStream * bit_stream_;
    InputStringStream * input_string_stream_;
};
