// generated by Designwerk EXI Converter 2022-06-22 15:02:41.203657
#pragma once

#include <cstdint>
#include <cstdio>
#include <string>
#include "base/bitstream.h"


class BaseTypes {
  public:

	BaseTypes(BitStream * bit_stream);
	virtual ~BaseTypes() = default;  // LCOV_EXCL_LINE

	virtual void injectHexBin(std::string);

	virtual std::string extractHexBin(uint8_t max_length);

	virtual uint32_t extractNBitsForEnum(uint32_t n_bits);

    virtual void injectNBitsForEnum(uint8_t value, uint8_t n_bits);

	virtual void injectString(std::string value);

	virtual std::string extractString();

	virtual void injectUri(std::string value);

	virtual std::string extractUri();

	virtual void injectIntegerNumber(int32_t number, bool is_unsigned);

	virtual int32_t extractIntegerNumber(uint8_t n_bytes, bool is_unsigned);

	virtual void injectBase64Value(std::string value);

	virtual std::string extractBase64Value();

	// / \brief writes the given boolean value to the bitstream
	virtual void injectBoolValue(bool);

	// / \brief read a bit from bitstream and returns the interpreted value
	virtual bool extractBoolValue();

	virtual void injectNBitNumber(int32_t number, uint8_t bits, int32_t offset);

	virtual int32_t extractNBitNumber(uint8_t bits, int32_t offset);

	virtual void check_event_code_is_0(std::string current_type_name);

	virtual uint8_t get_event_code_with_n_bits(int8_t n_bits, std::string current_type_name);

  private:
	BitStream * bit_stream_;
};
